apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: heybob-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/jucollet/heybob-deploy.git"
    targetRevision: main
    path: prod
  destination:
    server: "https://kubernetes.default.svc"
    namespace: heybob
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
