---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_DB
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  ports:
    - port: 5432
  selector:
    app: db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - port: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: app
          image: jucollet/hey-bob:VERSION
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              value: db
            - name: POSTGRES_PORT
              value: "5432"
            - name: PORT
              value: "3001"
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  type: ClusterIP
  ports:
    - port: 3001
  selector:
    app: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: messenger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messenger
  template:
    metadata:
      labels:
        app: messenger
    spec:
      containers:
        - name: messenger
          image: avoylenko/wwebjs-api:latest
          env:
            - name: SET_MESSAGES_AS_SEEN
              value: TRUE
            - name: ENABLE_LOCAL_CALLBACK_EXAMPLE
              value: FALSE
            - name: ENABLE_SWAGGER_ENDPOINT
              value: FALSE
            - name: RECOVER_SESSIONS
              value: TRUE
            - name: RATE_LIMIT_MAX
              value: 1000
            - name: BASE_WEBHOOK_URL
              value: http://app:3001/messenger-hook
            - name: MAX_ATTACHMENT_SIZE
              value: "5000000"
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MESSENGER_API_KEY
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: sessions
              mountPath: /usr/src/app/sessions
      volumes:
        - name: sessions
          persistentVolumeClaim:
            claimName: messenger-sessions-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: messenger
spec:
  type: ClusterIP
  ports:
    - port: 3000
  selector:
    app: messenger
